#!/usr/bin/env python

import sqlite3, string, sys, crypt, hmac, base64

dbfile="field_rascals.sqlite3"

	conn=sqlite3.connect(dbfile)
crsr=conn.cursor()
q="SELECT sn,salt,mac,crypt_hash FROM v_rasc ORDER BY sn DESC LIMIT 1"
crsr.execute(q)
while(1):
	row = crsr.fetchone()
	if (row==None):  break
	(SN,MAC,SALT,HASH) = row
crsr.close()
conn.close()

print SN
print MAC
print SALT
print HASH

#SN=xxx
#SALT=`dd if=/dev/random bs=4 count=1 2>/dev/null | xxd -p`
#cog -D "salt_val=1234567812345678" -D "mac_val=ab:cd:ef" -D "sn_val=012345" -r rascal_autogenerated.tpl
