/*[[[cog
import cog
import sqlite3, string, sys, crypt, hmac, base64

def get_random_salt(n):
	f = open('/dev/urandom','r')
	s = base64.b64encode( f.read(n+2) )
	s = s[0:n]
	f.close()
	return s

def calc_crypt_hash(s):
	return crypt.crypt(s,s[len(s)-2:])
 
def get_next_values():
	dbfile="field_rascals.sqlite3"
	conn=sqlite3.connect(dbfile)
	crsr=conn.cursor()
	SALT = get_random_salt(8);
	q = "INSERT INTO rascals (salt,crypt_hash) VALUES ('%s','%s')"%(SALT,calc_crypt_hash(SALT))
	#print q
	crsr.execute(q)
	conn.commit()
	crsr.close()
	conn.close()
	conn=sqlite3.connect(dbfile)
	crsr=conn.cursor()
	q="SELECT sn,mac,salt,crypt_hash FROM v_rascals ORDER BY sn DESC LIMIT 1"
	#print q
	crsr.execute(q)
	while(1):
		row = crsr.fetchone()
		if (row==None): 
			#print "Error - none on SELECT"
			break
		(SN,MAC,SALT,HASH) = row
	conn.commit()
	crsr.close()
	conn.close()
	return (SN,MAC,SALT,HASH)

# This is Python source to regenerate the rascal_autogenerated.h file from the template parameters below.
# Note that the placeholders are replaced by values from 'make_next_rascal.sh' -- which is updated after each successful build.
mac = '#define CONFIG_ETHADDR\t\t\t\t"02:03:04:%s"\t// MAC address'
sn =  '#define CONFIG_RASCAL_SERIAL\t\t\t"%06d"\t\t// sequential serial number'
salt ='#define CONFIG_RASCAL_SECURITY_CODE\t\t"%s"\t\t// 8-byte random hex salt for factory reset'
hash ='#define CONFIG_RASCAL_DEFAULT_ROOT_PW_HASH\t"%s"\t\t// Initial /etc/passwd value for root'
 
# Merge in the current MAC/SN/salt tuple remaining from last successful build
(sn_val,mac_val,salt_val,hash_val) = get_next_values()
mac = mac % mac_val
sn = sn % int(sn_val)
salt = salt % salt_val
hash = hash % hash_val

# Print out the current values
cog.outl('')
cog.outl(sn)
cog.outl(mac)
cog.outl(salt)
cog.outl(hash)
cog.outl('')
cog.outl('')
//	]]] */

#define CONFIG_RASCAL_SERIAL			"000050"		// sequential serial number
#define CONFIG_ETHADDR				"02:03:04:58:82:13"	// MAC address
#define CONFIG_RASCAL_SECURITY_CODE		"0N7rFaCr"		// 8-byte random hex salt for factory reset
#define CONFIG_RASCAL_DEFAULT_ROOT_PW_HASH	"CrgcjoZ6ljVTY"		// Initial /etc/passwd value for root


//	[[[end]]]
